### ISSUE TITLE
Invalid query parameter sent to Prowlarr

### ISSUE THREAD

**Issue by spiritualized** [swannie-eire/prowlarr-qbittorrent-plugin#3]
Prowlarr is sent a value of 0 for the `limit` parameter during all searches. `limit` should be a positive value, ideally with a default value of 50 or 100. This causes the request to fail for some data sources.

Prowlarr logs:
```
[Info] ReleaseSearchService: Searching indexer(s): [Test torznab 1, Test torznab 2] for Term: [my search term], Offset: 0, Limit: 0, Categories: []
```

**Comment by swannie-eire** [comment]
I no longer use prowlarr so cant test and resolve the issue as i use Jackett instead.

I will leave this open incase someone wants to fix it.

**Comment by swannie-eire** [comment]
REPO IS NO LONGER SUPPORTED
